services:
  bot1:
    build:
      context: ./bot
      dockerfile: dockerfile
    volumes:
      - ../controllers:/app/controllers
    stdin_open: true
    tty: true
    ports:
      - "5001:5001"  # Expose port 5000 in the container as 5001 on the host

  # bot2:
  #   build:
  #     context: ./bot
  #     dockerfile: dockerfile
  #   volumes:
  #     - ../controllers:/app/controllers
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - "5002:5000"  # Expose port 5000 in the container as 5002 on the host

  # bot3:
  #   build:
  #     context: ./bot
  #     dockerfile: dockerfile
  #   volumes:
  #     - ../controllers:/app/controllers
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - "5003:5000"  # Expose port 5000 in the container as 5003 on the host

  server:
    build:
      context: ./server
      dockerfile: dockerfile
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"  # Expose port 5000 for the server
    depends_on:
      - bot1
      # - bot2
      # - bot3